name: Codex Hunter - CI Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  validate-infrastructure:
    name: Validation Terraform
    runs-on: ubuntu-latest

    steps:
      - name: Recuperer le code
        uses: actions/checkout@v4

      - name: Installer Terraform sur le serveur du robot
        uses: hashicorp/setup-terraform@v3

      - name: Initialiser et Valider la syntaxe Terraform
        run: |
          cd terraform
          terraform init -backend=false
          terraform validate

  build-application:
    name: Verification Build Docker
    runs-on: ubuntu-latest

    steps:
      - name: Recuperer le code
        uses: actions/checkout@v4

      - name: Tester la construction de l'image Docker Frontend
        run: |
          echo "=== Verification du Dockerfile ==="
          docker build -t codex-hunter-frontend:test .
